import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import { Label } from "@/components/ui/label";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Header */}
          <header className="bg-background sticky top-0 z-50 flex justify-end p-4">
            <ModeToggle />
          </header>

          {/* Main Content */}
          <main className="container mx-auto flex-1">{children}</main>

          {/* Footer */}
          <footer className="bg-background sticky bottom-0 z-50 flex justify-end p-4">
            <Label>Created by ilaumjd</Label>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
